# Cloudflare Pages Build Configuration
# https://developers.cloudflare.com/pages/platform/build-configuration/

name = "studious-wafflekavach"
pages_build_output_dir = "dist"
compatibility_date = "2026-04-02"

[vars]
BUN_VERSION = "0"
NODE_VERSION = "22"
NPM_FLAGS = "--no-frozen-lockfile"
