import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "kn" | "hi" | "mr";

export const LANGUAGE_CONFIG: Record<Language, { name: string; nativeName: string; flag: string; speechCode: string }> = {
  en: { name: "English", nativeName: "English", flag: "🇬🇧", speechCode: "en-IN" },
  kn: { name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳", speechCode: "kn-IN" },
  hi: { name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳", speechCode: "hi-IN" },
  mr: { name: "Marathi", nativeName: "मराठी", flag: "🇮🇳", speechCode: "mr-IN" },
};

interface LanguageContextType {
  language: Language | null;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  speechCode: string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

// All translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "Rakshakavach",
    appTagline: "Secure Money Transfer",
    newAccount: "Open New Account",
    login: "Login",
    phoneNumber: "Phone Number",
    sendOtp: "Send OTP",
    enterOtp: "Enter OTP",
    verify: "Verify",
    yourName: "Your Name",
    typeNamePlaceholder: "Type your name",
    speakName: "🎤 Speak Name",
    continue: "Continue",
    setPin: "🔐 Set 4-digit PIN",
    enterPin: "🔐 Enter PIN",
    back: "Back",
    newAccountTitle: "New Account",
    loginTitle: "Login",
    askMobileNumber: "What is your mobile number?",
    sendSecurityCodeText: "We will send you a security code.",
    speakYourNumber: "Or speak your number",
    speakYourOtp: "Or speak your OTP",
    speakPin: "Or speak your PIN",
    sentOtpText: "We've sent a 6-digit verification code to your registered mobile number.",
    resendCode: "Resend Code",
    standardRatesApplies: "Standard messaging rates may apply for OTP SMS.",
    e2eEncryption: "End-to-End Encryption",
    bitSecurity: "256-bit Security",
    loading: "Loading...",
    enter10Digits: "Enter 10-digit phone number",
    wrongOtp: "Wrong OTP",
    enterName: "Enter name",
    fetchingName: "Searching...",
    alreadyRegistered: "This number is already registered",
    errorOccurred: "An error occurred",
    userNotFound: "User not found",
    accountLocked: "Account is locked",
    wrongPin: "Wrong PIN",
    attemptsLeft: "attempts left",
    threeWrongAttempts: "3 wrong attempts - Account locked",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    balance: "Balance",
    totalDepositBalance: "Total Deposit Balance",
    showBalances: "Show Balances",
    hideBalances: "Hide Balances",
    savingsAccount: "Savings Account",
    deposits: "Deposits",
    quickTasks: "Quick Tasks",
    sendMoney: "💰 Send Money",
    sendMoneyLabel: "Send Money",
    receiveMoney: "📥 Receive",
    receiveLabel: "Receive",
    scanQr: "Scan QR",
    checkBalance: "Check Balance",
    history: "📜 History",
    historyLabel: "History",
    emergencyLock: "🆘 Emergency Lock",
    emergencyLabel: "Emergency",
    guardianHelp: "Guardian Help",
    fraudHelp: "Kavach (UPI Scan Detector)",
    logoutLabel: "Logout",
    profileLabel: "Profile",
    tapOrSpeak: "Tap a box or speak your command",
    sosBlockedMsg: "Account is blocked! Enter your PIN to unlock.",
    shareYourNumber: "Share your phone number to receive money",
    yourNumber: "Your number",
    receiverNumber: "Receiver's Number",
    speakNumber: "🎤 Speak Number",
    amount: "Amount (₹)",
    balanceLabel: "Balance",
    confirm: "✓ Confirm",
    wrongPinError: "Wrong PIN",
    receiverNotFound: "Receiver not found",
    transactionFailed: "Transaction failed",
    transactionSuccess: "Transaction Successful!",
    goHome: "🏠 Go Home",
    enterValidAmount: "Enter valid amount",
    insufficientBalance: "Insufficient balance",
    cantSendToSelf: "Cannot send to your own number",
    pinHighRisk: "🔐 Enter PIN (High Risk)",
    transactionHistory: "Transaction History",
    noTransactions: "No transactions",
    risk: "Risk",
    warning: "Warning",
    emergency: "🆘 Emergency",
    accountIsLocked: "Account is Locked",
    unlockAccount: "Unlock Account",
    enterPinToUnlock: "🔐 Enter PIN to unlock",
    lockAccountDesc: "Lock account immediately if in danger",
    lockAccount: "🔒 Lock Account",
    safe: "🟢 Safe",
    caution: "🟡 Caution",
    danger: "🔴 Danger",
    proceedCarefully: "Please proceed carefully",
    voiceWelcome: "Welcome to Rakshakavach",
    voiceAskName: "Please say your name",
    voiceAskPin: "Please enter your PIN",
    voiceLoginSuccess: "Login successful",
    voiceConfirmTx: "You are sending ₹{amount} to {phone}",
    voiceFraudWarning: "This may be a risky transaction",
    voiceAccountLocked: "Account has been locked",
    voiceAccountUnlocked: "Account has been unlocked",
    voiceTxSuccess: "Transaction successful",
    voiceInsufficientBalance: "Insufficient balance",
    voiceShareNumber: "Share your phone number",
    voiceNotAvailable: "Voice recognition not available",
    isoCertified: "ISO 27001 Certified Protection",
    nextGenEncryption: "Next-Gen Encryption",
    encryptionDesc: "Your transactions are guarded by military-grade asymmetric encryption and real-time fraud monitoring.",
    trustVerified: "Trust Verified",
    trustDesc: "Join over 2 million users who trust Rakshakavach for their daily financial operations.",
    homeTab: "Home",
    vaultTab: "Vault",
    shieldTab: "Shield",
    profileTab: "Profile",
    verifyingIdentity: "Verifying Identity...",
    checkingSecurity: "Checking Security...",
    accessGranted: "Access Granted",
    pinTaken: "This PIN is already used. Please choose a different PIN.",
    highRiskCheck: "High Risk! Please check the details once again.",
    guardianHelpTitle: "Guardian Help / ಸಹಾಯ ಕೇಂದ್ರ",
    emergencyHelpTitle: "🆘 Emergency Help",
    lockAccountLabel: "Lock Account",
    helpLockAccountDesc: "Press this button to immediately lock your account.",
    customerCareLabel: "Customer Care",
    customerCareDesc: "Call 24/7 for assistance.",
    fraudProtectionTitle: "Fraud Protection",
    neverShareOtpLabel: "Never Share OTP",
    neverShareOtpDesc: "Bank or anyone will never ask for your OTP.",
    bewareCallsLabel: "Beware of Unknown Calls",
    bewareCallsDesc: "Don't send money to unknown persons.",
    suspiciousTxLabel: "Suspicious Transaction",
    suspiciousTxDesc: "Immediately lock account and get help.",
    guardianAssistTitle: "Guardian Assistant",
    callGuardianLabel: "Call Guardian",
    callGuardianDesc: "Get help from your family members.",
    permissionReqLabel: "Permission Required",
    permissionReqDesc: "High value transactions need guardian permission.",
    guidanceTitle: "Help & Guidance",
    howToSendLabel: "How to Send Money",
    howToSendDesc: "Click Send Money, enter number and amount.",
    useQrLabel: "Using QR Code",
    useQrDesc: "Scan and send money easily.",
    forgotPinLabel: "Forgot PIN",
    forgotPinDesc: "Contact help center to reset.",
  },
  kn: {
    appName: "ರಕ್ಷಾಕವಚ",
    appTagline: "ಸುರಕ್ಷಿತ ಹಣ ವರ್ಗಾವಣೆ",
    newAccount: "ಹೊಸ ಖಾತೆ ತೆರೆಯಿರಿ",
    login: "ಲಾಗಿನ್",
    phoneNumber: "ಫೋನ್ ನಂಬರ್",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    enterOtp: "OTP ನಮೂದಿಸಿ",
    verify: "ಪರಿಶೀಲಿಸಿ",
    yourName: "ನಿಮ್ಮ ಹೆಸರು",
    typeNamePlaceholder: "ಹೆಸರು ಟೈಪ್ ಮಾಡಿ",
    speakName: "🎤 ಹೆಸರು ಹೇಳಿ",
    continue: "ಮುಂದುವರಿಯಿರಿ",
    setPin: "🔐 4 ಅಂಕಿ PIN ಸೆಟ್ ಮಾಡಿ",
    enterPin: "🔐 PIN ನಮೂದಿಸಿ",
    back: "ಹಿಂದಕ್ಕೆ",
    newAccountTitle: "ಹೊಸ ಖಾತೆ",
    loginTitle: "ಲಾಗಿನ್",
    askMobileNumber: "ನಿಮ್ಮ ಮೊಬೈಲ್ ನಂಬರ್ ಏನು?",
    sendSecurityCodeText: "ನಾವು ನಿಮಗೆ ಭದ್ರತಾ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ.",
    speakYourNumber: "ಅಥವಾ ನಿಮ್ಮ ಸಂಖ್ಯೆಯನ್ನು ಹೇಳಿ",
    speakYourOtp: "ಅಥವಾ ನಿಮ್ಮ OTP ಹೇಳಿ",
    speakPin: "ಅಥವಾ ನಿಮ್ಮ PIN ಹೇಳಿ",
    sentOtpText: "ನಿಮ್ಮ ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಗೆ 6-ಅಂಕಿಯ ಪರಿಶೀಲನಾ ಕೋಡ್ ಅನ್ನು ಕಳುಹಿಸಲಾಗಿದೆ.",
    resendCode: "ಮತ್ತೆ ಕೋಡ್ ಕಳುಹಿಸಿ",
    standardRatesApplies: "OTP SMS ಗಾಗಿ ಪ್ರಮಾಣಿತ ಶುಲ್ಕಗಳು ಅನ್ವಯಿಸಬಹುದು.",
    e2eEncryption: "ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್",
    bitSecurity: "256-ಬಿಟ್ ಭದ್ರತೆ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    enter10Digits: "10 ಅಂಕಿಗಳ ಫೋನ್ ನಂಬರ್ ನಮೂದಿಸಿ",
    wrongOtp: "ತಪ್ಪಾದ OTP",
    enterName: "ಹೆಸರು ನಮೂದಿಸಿ",
    fetchingName: "ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    alreadyRegistered: "ಈ ಸಂಖ್ಯೆ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲ್ಪಟ್ಟಿದೆ",
    errorOccurred: "ದೋಷ ಸಂಭವಿಸಿದೆ",
    userNotFound: "ಬಳಕೆದಾರ ಕಂಡುಬಂದಿಲ್ಲ",
    accountLocked: "ಖಾತೆ ಲಾಕ್ ಆಗಿದೆ",
    wrongPin: "ತಪ್ಪಾದ PIN",
    attemptsLeft: "ಪ್ರಯತ್ನ ಉಳಿದಿದೆ",
    threeWrongAttempts: "3 ತಪ್ಪು ಪ್ರಯತ್ನಗಳು - ಖಾತೆ ಲಾಕ್ ಆಗಿದೆ",
    goodMorning: "ಶುಭೋದಯ",
    goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ",
    balance: "ಬ್ಯಾಲೆನ್ಸ್",
    totalDepositBalance: "ಒಟ್ಟು ಠೇವಣಿ ಬ್ಯಾಲೆನ್ಸ್",
    showBalances: "ಬ್ಯಾಲೆನ್ಸ್ ತೋರಿಸಿ",
    hideBalances: "ಬ್ಯಾಲೆನ್ಸ್ ಮರೆಮಾಡಿ",
    savingsAccount: "ಉಳಿತಾಯ ಖಾತೆ",
    deposits: "ಠೇವಣಿಗಳು",
    quickTasks: "ತ್ವರಿತ ಕಾರ್ಯಗಳು",
    sendMoney: "💰 ಹಣ ಕಳುಹಿಸಿ",
    sendMoneyLabel: "ಹಣ ಕಳುಹಿಸಿ",
    receiveMoney: "📥 ಹಣ ಸ್ವೀಕರಿಸಿ",
    receiveLabel: "ಸ್ವೀಕರಿಸಿ",
    scanQr: "QR ಸ್ಕ್ಯಾನ್",
    checkBalance: "ಬ್ಯಾಲೆನ್ಸ್ ಪರಿಶೀಲಿಸಿ",
    history: "📜 ಇತಿಹಾಸ",
    historyLabel: "ಇತಿಹಾಸ",
    emergencyLock: "🆘 ಖಾತೆ ಲಾಕ್",
    emergencyLabel: "ತುರ್ತು",
    guardianHelp: "ರಕ್ಷಕ ಸಹಾಯ",
    fraudHelp: "ಕವಚ (UPI ಸ್ಕ್ಯಾನ್ ಡಿಟೆಕ್ಟರ್)",
    logoutLabel: "ಲಾಗ್ ಔಟ್",
    profileLabel: "ಪ್ರೊಫೈಲ್",
    tapOrSpeak: "ಬಾಕ್ಸ್ ಟ್ಯಾಪ್ ಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಆದೇಶ ಹೇಳಿ",
    sosBlockedMsg: "ಖಾತೆ ಬ್ಲಾಕ್ ಆಗಿದೆ! ಅನ್‌ಲಾಕ್ ಮಾಡಲು ನಿಮ್ಮ PIN ನಮೂದಿಸಿ.",
    shareYourNumber: "ಹಣ ಸ್ವೀಕರಿಸಲು ನಿಮ್ಮ ಫೋನ್ ನಂಬರ್ ಹಂಚಿಕೊಳ್ಳಿ",
    yourNumber: "ನಿಮ್ಮ ನಂಬರ್",
    receiverNumber: "ಸ್ವೀಕರಿಸುವವರ ನಂಬರ್",
    speakNumber: "🎤 ನಂಬರ್ ಹೇಳಿ",
    amount: "ಮೊತ್ತ (₹)",
    balanceLabel: "ಬ್ಯಾಲೆನ್ಸ್",
    confirm: "✓ ದೃಢೀಕರಿಸಿ",
    wrongPinError: "ತಪ್ಪಾದ PIN",
    receiverNotFound: "ಸ್ವೀಕರಿಸುವವರು ಕಂಡುಬಂದಿಲ್ಲ",
    transactionFailed: "ವ್ಯವಹಾರ ವಿಫಲವಾಗಿದೆ",
    transactionSuccess: "ವ್ಯವಹಾರ ಯಶಸ್ವಿ!",
    goHome: "🏠 ಹೋಂ ಗೆ ಹೋಗಿ",
    enterValidAmount: "ಮಾನ್ಯ ಮೊತ್ತ ನಮೂದಿಸಿ",
    insufficientBalance: "ಸಾಕಷ್ಟು ಬ್ಯಾಲೆನ್ಸ್ ಇಲ್ಲ",
    cantSendToSelf: "ನಿಮ್ಮದೇ ನಂಬರ್ ಗೆ ಕಳುಹಿಸಲಾಗುವುದಿಲ್ಲ",
    pinHighRisk: "🔐 PIN ನಮೂದಿಸಿ (ಹೆಚ್ಚಿನ ಅಪಾಯ)",
    transactionHistory: "ವ್ಯವಹಾರ ಇತಿಹಾಸ",
    noTransactions: "ಯಾವುದೇ ವ್ಯವಹಾರಗಳಿಲ್ಲ",
    risk: "ಅಪಾಯ",
    warning: "ಎಚ್ಚರಿಕೆ",
    emergency: "🆘 ತುರ್ತು",
    accountIsLocked: "ಖಾತೆ ಲಾಕ್ ಆಗಿದೆ",
    unlockAccount: "ಅನ್‌ಲಾಕ್ ಮಾಡಿ",
    enterPinToUnlock: "🔐 PIN ನಮೂದಿಸಿ ಅನ್‌ಲಾಕ್ ಮಾಡಲು",
    lockAccountDesc: "ಅಪಾಯವಿದ್ದರೆ ಖಾತೆಯನ್ನು ತಕ್ಷಣ ಲಾಕ್ ಮಾಡಿ",
    lockAccount: "🔒 ಖಾತೆ ಲಾಕ್ ಮಾಡಿ",
    safe: "🟢 ಸುರಕ್ಷಿತ",
    caution: "🟡 ಎಚ್ಚರಿಕೆ",
    danger: "🔴 ಅಪಾಯ",
    proceedCarefully: "ದಯವಿಟ್ಟು ಜಾಗರೂಕರಾಗಿ ಮುಂದುವರಿಯಿರಿ",
    voiceWelcome: "ರಕ್ಷಾಕವಚ ಗೆ ಸ್ವಾಗತ",
    voiceAskName: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರು ಹೇಳಿ",
    voiceAskPin: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಿನ್ ನಮೂದಿಸಿ",
    voiceLoginSuccess: "ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ",
    voiceConfirmTx: "ನೀವು ₹{amount} ಅನ್ನು {phone} ಅವರಿಗೆ ಕಳುಹಿಸುತ್ತಿದ್ದೀರಿ",
    voiceFraudWarning: "ಈ ವ್ಯವಹಾರ ಅಪಾಯಕರವಾಗಿರಬಹುದು",
    voiceAccountLocked: "ಭದ್ರತೆಯ ದೃಷ್ಟಿಯಿಂದ ನಿಮ್ಮ ಖಾತೆಯನ್ನ ಲಾಕ್ ಮಾಡಲಾಗಿದೆ",
    voiceAccountUnlocked: "ನಿಮ್ಮ ಖಾತೆ ಅನ್‌ಲಾಕ್ ಆಗಿದೆ",
    voiceTxSuccess: "ನಿಮ್ಮ ವ್ಯವಹಾರ ಯಶಸ್ವಿಯಾಗಿದೆ",
    voiceInsufficientBalance: "ಕ್ಷಮಿಸಿ, ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ಸಾಕಷ್ಟು ಹಣ ಇಲ್ಲ",
    voiceShareNumber: "ನಿಮ್ಮ ಫೋನ್ ನಂಬರ್ ಹಂಚಿಕೊಳ್ಳಿ",
    voiceNotAvailable: "ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಲಭ್ಯವಿಲ್ಲ",
    isoCertified: "ISO 27001 ಪ್ರಮಾಣೀಕೃತ ರಕ್ಷಣೆ",
    nextGenEncryption: "ನೆಕ್ಸ್ಟ್-ಜೆನ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್",
    encryptionDesc: "ನಿಮ್ಮ ವಹಿವಾಟುಗಳನ್ನು ಮಿಲಿಟರಿ-ಗ್ರೇಡ್ ಅಸಿಮ್ಮೆಟ್ರಿಕ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್ ಮತ್ತು ರಿಯಲ್-ಟೈಮ್ ವಂಚನೆ ಮೇಲ್ವಿಚಾರಣೆಯಿಂದ ರಕ್ಷಿಸಲಾಗಿದೆ.",
    trustVerified: "ನಂಬಿಕೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    trustDesc: "ತಮ್ಮ ದೈನಂದಿನ ಹಣಕಾಸು ಕಾರ್ಯಾಚರಣೆಗಳಿಗಾಗಿ ರಕ್ಷಾಕವಚವನ್ನು ನಂಬುವ 2 ಮಿಲಿಯನ್‌ಗಿಂತಲೂ ಹೆಚ್ಚು ಬಳಕೆದಾರರೊಂದಿಗೆ ಸೇರಿ.",
    homeTab: "ಹೋಮ್",
    vaultTab: "ವಾಲ್ಟ್",
    shieldTab: " ಶೀಲ್ಡ್",
    profileTab: " ಪ್ರೊಫೈಲ್",
    verifyingIdentity: "ಗುರುತು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    checkingSecurity: "ಭದ್ರತೆ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    accessGranted: "ಪ್ರವೇಶ ಮಂಜೂರು ಮಾಡಲಾಗಿದೆ",
    pinTaken: "ಈ PIN ಈಗಾಗಲೇ ಬಳಕೆಯಲ್ಲಿದೆ. ದಯವಿಟ್ಟು ಬೇರೆ PIN ಆಯ್ಕೆ ಮಾಡಿ.",
    highRiskCheck: "ಹೆಚ್ಚಿನ ಅಪಾಯ! ದಯವಿಟ್ಟು ವಿವರಗಳನ್ನು ಮತ್ತೊಮ್ಮೆ ಪರಿಶೀಲಿಸಿ.",
    guardianHelpTitle: "Guardian Help / ಸಹಾಯ ಕೇಂದ್ರ",
    emergencyHelpTitle: "🆘 ತುರ್ತು ಸಹಾಯ",
    lockAccountLabel: "ಖಾತೆ ಲಾಕ್ ಮಾಡಿ",
    helpLockAccountDesc: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ತಕ್ಷಣ ಲಾಕ್ ಮಾಡಲು ಈ ಬಟನ್ ಒತ್ತಿರಿ",
    customerCareLabel: "ಗ್ರಾಹಕ ಸಹಾಯ ಸಂಖ್ಯೆ",
    customerCareDesc: "24/7 ಸಹಾಯಕ್ಕಾಗಿ ಕರೆ ಮಾಡಿ",
    fraudProtectionTitle: "⚠️ ಮೋಸದಿಂದ ರಕ್ಷಣೆ",
    neverShareOtpLabel: "OTP ಯಾರಿಗೂ ಹೇಳಬೇಡಿ",
    neverShareOtpDesc: "ಬ್ಯಾಂಕ್ ಅಥವಾ ಯಾರೂ OTP ಕೇಳುವುದಿಲ್ಲ",
    bewareCallsLabel: "ಅಪರಿಚಿತ ಕರೆಗಳಿಂದ ಜಾಗರೂಕರಾಗಿ",
    bewareCallsDesc: "ಅಪರಿಚಿತ ವ್ಯಕ್ತಿಗಳಿಗೆ ಹಣ ಕಳುಹಿಸಬೇಡಿ",
    suspiciousTxLabel: "ಸಂದೇಹಾಸ್ಪದ ವ್ಯವಹಾರ",
    suspiciousTxDesc: "ತಕ್ಷಣ ಖಾತೆಯನ್ನು ಲಾಕ್ ಮಾಡಿ ಮತ್ತು ಸಹಾಯ ಪಡೆಯಿರಿ",
    guardianAssistTitle: "👨‍👩‍👧 ಸಂರಕ್ಷಕ ಸಹಾಯ",
    callGuardianLabel: "ಸಂರಕ್ಷಕನಿಗೆ ಕರೆ ಮಾಡಿ",
    callGuardianDesc: "ನಿಮ್ಮ ಕುಟುಂಬ ಸದಸ್ಯರ ಸಹಾಯ ಪಡೆಯಿರಿ",
    permissionReqLabel: "ಅನುಮತಿ ಅಗತ್ಯವಿರುವ ವ್ಯವಹಾರಗಳು",
    permissionReqDesc: "ಹೆಚ್ಚು ಮೊತ್ತದ ವ್ಯವಹಾರಗಳಿಗೆ ಸಂರಕ್ಷಕ ಅನುಮತಿ ಬೇಕಾಗುತ್ತದೆ",
    guidanceTitle: "📘 ಸಹಾಯ ಮತ್ತು ಮಾರ್ಗದರ್ಶನ",
    howToSendLabel: "ಹಣ ಹೇಗೆ ಕಳುಹಿಸಬೇಕು",
    howToSendDesc: "Send Money ಕ್ಲಿಕ್ ಮಾಡಿ, ಸಂಖ್ಯೆ ಮತ್ತು ಮೊತ್ತ ನಮೂದಿಸಿ",
    useQrLabel: "QR ಕೋಡ್ ಬಳಸುವುದು",
    useQrDesc: "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಸುಲಭವಾಗಿ ಹಣ ಕಳುಹಿಸಿ",
    forgotPinLabel: "PIN ಮರೆತಿದ್ದರೆ",
    forgotPinDesc: "ಪುನಃ ಸೆಟ್ ಮಾಡಲು ಸಹಾಯ ಕೇಂದ್ರ ಸಂಪರ್ಕಿಸಿ",
  },
  hi: {
    appName: "रक्षाकवच",
    appTagline: "सुरक्षित पैसे भेजें",
    newAccount: "नया खाता खोलें",
    login: "लॉगिन",
    phoneNumber: "फ़ोन नंबर",
    sendOtp: "OTP भेजें",
    enterOtp: "OTP दर्ज करें",
    verify: "सत्यापित करें",
    yourName: "आपका नाम",
    typeNamePlaceholder: "नाम टाइप करें",
    speakName: "🎤 नाम बोलें",
    continue: "आगे बढ़ें",
    setPin: "🔐 4 अंक PIN सेट करें",
    enterPin: "🔐 PIN दर्ज करें",
    back: "वापस",
    newAccountTitle: "नया खाता",
    loginTitle: "लॉगिन",
    askMobileNumber: "आपका मोबाइल नंबर क्या है?",
    sendSecurityCodeText: "हम आपको एक सुरक्षा कोड भेजेंगे।",
    speakYourNumber: "या अपना नंबर बोलें",
    speakYourOtp: "या अपना OTP बोलें",
    speakPin: "या अपना PIN बोलें",
    sentOtpText: "हमने आपके पंजीकृत मोबाइल नंबर पर 6 अंकों का सत्यापन कोड भेजा है।",
    resendCode: "कोड को फिर से भेजें",
    standardRatesApplies: "OTP SMS के लिए मानक मैसेजिंग दरें लागू हो सकती हैं।",
    e2eEncryption: "एंड-टू-एंड एन्क्रिप्शन",
    bitSecurity: "256-बिट सुरक्षा",
    loading: "लोड हो रहा है...",
    enter10Digits: "10 अंकों का फ़ोन नंबर दर्ज करें",
    wrongOtp: "गलत OTP",
    enterName: "नाम दर्ज करें",
    fetchingName: "खोज रहे हैं...",
    alreadyRegistered: "यह नंबर पहले से पंजीकृत है",
    errorOccurred: "एक त्रुटि हुई",
    userNotFound: "उपयोगकर्ता नहीं मिला",
    accountLocked: "खाता लॉक है",
    wrongPin: "गलत PIN",
    attemptsLeft: "प्रयास शेष",
    threeWrongAttempts: "3 गलत प्रयास - खाता लॉक",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    balance: "बैलेंस",
    totalDepositBalance: "कुल जमा शेष",
    showBalances: "बैलेंस दिखाएं",
    hideBalances: "बैलेंस छुपाएं",
    savingsAccount: "बचत खाता",
    deposits: "जमा",
    quickTasks: "त्वरित कार्य",
    sendMoney: "💰 पैसे भेजें",
    sendMoneyLabel: "पैसे भेजें",
    receiveMoney: "📥 पैसे प्राप्त करें",
    receiveLabel: "प्राप्त करें",
    scanQr: "QR स्कैन",
    checkBalance: "बैलेंस जांचें",
    history: "📜 इतिहास",
    historyLabel: "इतिहास",
    emergencyLock: "🆘 खाता लॉक",
    emergencyLabel: "आपातकाल",
    guardianHelp: "अभिभावक सहायता",
    fraudHelp: "कवच (UPI स्कैन डिटेक्टर)",
    logoutLabel: "लॉग आउट",
    profileLabel: "प्रोफ़ाइल",
    tapOrSpeak: "बॉक्स पर टैप करें या अपना कमांड बोलें",
    sosBlockedMsg: "खाता ब्लॉक है! अनलॉक करने के लिए अपना PIN डालें।",
    shareYourNumber: "पैसे प्राप्त करने के लिए अपना फ़ोन नंबर साझा करें",
    yourNumber: "आपका नंबर",
    receiverNumber: "प्राप्तकर्ता का नंबर",
    speakNumber: "🎤 नंबर बोलें",
    amount: "राशि (₹)",
    balanceLabel: "बैलेंस",
    confirm: "✓ पुष्टि करें",
    wrongPinError: "गलत PIN",
    receiverNotFound: "प्राप्तकर्ता नहीं मिला",
    transactionFailed: "लेनदेन विफल",
    transactionSuccess: "लेनदेन सफल!",
    goHome: "🏠 होम पर जाएं",
    enterValidAmount: "सही राशि दर्ज करें",
    insufficientBalance: "पर्याप्त बैलेंस नहीं",
    cantSendToSelf: "अपने ही नंबर पर नहीं भेज सकते",
    pinHighRisk: "🔐 PIN दर्ज करें (उच्च जोखिम)",
    transactionHistory: "लेनदेन इतिहास",
    noTransactions: "कोई लेनदेन नहीं",
    risk: "खतरा",
    warning: "चेतावनी",
    emergency: "🆘 आपातकाल",
    accountIsLocked: "खाता लॉक है",
    unlockAccount: "अनलॉक करें",
    enterPinToUnlock: "🔐 अनलॉक करने के लिए PIN दर्ज करें",
    lockAccountDesc: "खतरे में हो तो तुरंत खाता लॉक करें",
    lockAccount: "🔒 खाता लॉक करें",
    safe: "🟢 सुरक्षित",
    caution: "🟡 सावधान",
    danger: "🔴 खतरा",
    proceedCarefully: "कृपया सावधानी से आगे बढ़ें",
    voiceWelcome: "रक्षाकवच में आपका स्वागत है",
    voiceAskName: "अपना नाम बोलें",
    voiceAskPin: "अपना PIN दर्ज करें",
    voiceLoginSuccess: "लॉगिन सफल",
    voiceConfirmTx: "आप ₹{amount} को {phone} पर भेज रहे हैं",
    voiceFraudWarning: "यह एक जोखिम भरा लेनदेन हो सकता है",
    voiceAccountLocked: "खाता लॉक कर दिया गया है",
    voiceAccountUnlocked: "खाता अनलॉक हो गया है",
    voiceTxSuccess: "लेनदेन सफल",
    voiceInsufficientBalance: "पर्याप्त बैलेंस नहीं",
    voiceShareNumber: "अपना फ़ोन नंबर साझा करें",
    voiceNotAvailable: "आवाज़ पहचान उपलब्ध नहीं",
    isoCertified: "ISO 27001 प्रमाणित सुरक्षा",
    nextGenEncryption: "नेक्स्ट-जेन एन्क्रिप्शन",
    encryptionDesc: "आपके लेनदेन को सैन्य-ग्रेड असममित एन्क्रिप्शन और वास्तविक समय की धोखाधड़ी निगरानी द्वारा सुरक्षित किया जाता है।",
    trustVerified: "विश्वास प्रमाणित",
    trustDesc: "उन 2 मिलियन से अधिक उपयोगकर्ताओं में शामिल हों जो अपने दैनिक वित्तीय कार्यों के लिए रक्षाकवच पर भरोसा करते हैं।",
    homeTab: "होम",
    vaultTab: "वॉल्ट",
    shieldTab: "शील्ड",
    profileTab: "प्रोफ़ाइल",
    highRiskCheck: "उच्च जोखिम! कृपया विवरण एक बार फिर से जांचें।",
    guardianHelpTitle: "Guardian Help / ಸಹಾಯ ಕೇಂದ್ರ",
    emergencyHelpTitle: "🆘 आपातकालीन सहायता",
    lockAccountLabel: "खाता लॉक करें",
    helpLockAccountDesc: "अपने खाते को तुरंत लॉक करने के लिए इस बटन को दबाएं।",
    customerCareLabel: "कस्टमर केयर",
    customerCareDesc: "सहायता के लिए 24/7 कॉल करें।",
    fraudProtectionTitle: "⚠️ धोखाधड़ी से सुरक्षा",
    neverShareOtpLabel: "OTP कभी साझा न करें",
    neverShareOtpDesc: "बैंक या कोई भी कभी भी आपका OTP नहीं मांगेगा।",
    bewareCallsLabel: "अपरिचित कॉलों से सावधान रहें",
    bewareCallsDesc: "अपरिचित व्यक्तियों को पैसे न भेजें।",
    suspiciousTxLabel: "संदिग्ध लेनदेन",
    suspiciousTxDesc: "खाता तुरंत लॉक करें और सहायता लें।",
    guardianAssistTitle: "👨‍👩‍👧 अभिभावक सहायक",
    callGuardianLabel: "अभिभावक को कॉल करें",
    callGuardianDesc: "अपने परिवार के सदस्यों से सहायता प्राप्त करें।",
    permissionReqLabel: "अनुमति आवश्यक",
    permissionReqDesc: "उच्च मूल्य के लेनदेन के लिए अभिभावक की अनुमति की आवश्यकता होती है।",
    guidanceTitle: "📘 सहायता एवं मार्गदर्शन",
    howToSendLabel: "पैसे कैसे भेजें",
    howToSendDesc: "पैसे भेजें पर क्लिक करें, नंबर और राशि दर्ज करें।",
    useQrLabel: "QR कोड का उपयोग करना",
    useQrDesc: "स्कॅन करें और आसानी से पैसे भेजें।",
    forgotPinLabel: "PIN भूल गए",
    forgotPinDesc: "रीसेट करने के लिए हेल्प सेंटर से संपर्क करें।",
  },
  mr: {
    appName: "रक्षाकवच",
    appTagline: "सुरक्षित पैसे हस्तांतरण",
    newAccount: "नवीन खाते उघडा",
    login: "लॉगिन",
    phoneNumber: "फोन नंबर",
    sendOtp: "OTP पाठवा",
    enterOtp: "OTP प्रविष्ट करा",
    verify: "सत्यापित करा",
    yourName: "तुमचे नाव",
    typeNamePlaceholder: "नाव टाइप करा",
    speakName: "🎤 नाव सांगा",
    continue: "पुढे जा",
    setPin: "🔐 4 अंकी PIN सेट करा",
    enterPin: "🔐 PIN प्रविष्ट करा",
    back: "मागे",
    newAccountTitle: "नवीन खाते",
    loginTitle: "लॉगिन",
    askMobileNumber: "तुमचा मोबाईल नंबर काय आहे?",
    sendSecurityCodeText: "आम्ही तुम्हाला एक सुरक्षा कोड पाठवू.",
    speakYourNumber: "किंवा तुमचा नंबर सांगा",
    speakYourOtp: "किंवा तुमचा OTP सांगा",
    speakPin: "किंवा तुमचा PIN सांगा",
    sentOtpText: "आम्ही तुमच्या नोंदणीकृत मोबाइल नंबरवर 6-अंकी पडताळणी कोड पाठवला आहे.",
    resendCode: "कोड पुन्हा पाठवा",
    standardRatesApplies: "OTP SMS साठी मानक संदेशन दर लागू होऊ शकतात.",
    e2eEncryption: "एंड-टू-एंड एन्क्रिप्शन",
    bitSecurity: "256-बिट सुरक्षा",
    loading: "लोड होत आहे...",
    enter10Digits: "10 अंकी फोन नंबर प्रविष्ट करा",
    wrongOtp: "चुकीचा OTP",
    enterName: "नाव प्रविष्ट करा",
    fetchingName: "शोधत आहे...",
    alreadyRegistered: "हा नंबर आधीच नोंदणीकृत आहे",
    errorOccurred: "एक त्रुटी आली",
    userNotFound: "वापरकर्ता सापडला नाही",
    accountLocked: "खाते लॉक आहे",
    wrongPin: "चुकीचा PIN",
    attemptsLeft: "प्रयत्न शिल्लक",
    threeWrongAttempts: "3 चुकीचे प्रयत्न - खाते लॉक",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दुपार",
    goodEvening: "शुभ संध्याकाळ",
    balance: "शिल्लक",
    totalDepositBalance: "एकूण ठेव शिल्लक",
    showBalances: "शिल्लक दाखवा",
    hideBalances: "शिल्लक लपवा",
    savingsAccount: "बचत खाते",
    deposits: "ठेवी",
    quickTasks: "जलद कार्ये",
    sendMoney: "💰 पैसे पाठवा",
    sendMoneyLabel: "पैसे पाठवा",
    receiveMoney: "📥 पैसे घ्या",
    receiveLabel: "प्राप्त करा",
    scanQr: "QR स्कॅन",
    checkBalance: "शिल्लक तपासा",
    history: "📜 इतिहास",
    historyLabel: "इतिहास",
    emergencyLock: "🆘 खाते लॉक",
    emergencyLabel: "आणीबाणी",
    guardianHelp: "पालक मदत",
    fraudHelp: "कवच (UPI स्कॅन डिटेक्टर)",
    logoutLabel: "लॉग आउट",
    profileLabel: "प्रोफाइल",
    tapOrSpeak: "बॉक्सवर टॅप करा किंवा तुमचा आदेश सांगा",
    sosBlockedMsg: "खाते ब्लॉक आहे! अनलॉक करण्यासाठी तुमचा PIN प्रविष्ट करा.",
    shareYourNumber: "पैसे घेण्यासाठी तुमचा फोन नंबर शेअर करा",
    yourNumber: "तुमचा नंबर",
    receiverNumber: "प्राप्तकर्त्याचा नंबर",
    speakNumber: "🎤 नंबर सांगा",
    amount: "रक्कम (₹)",
    balanceLabel: "शिल्लक",
    confirm: "✓ पुष्टी करा",
    wrongPinError: "चुकीचा PIN",
    receiverNotFound: "प्राप्तकर्ता सापडला नाही",
    transactionFailed: "व्यवहार अयशस्वी",
    transactionSuccess: "व्यवहार यशस्वी!",
    goHome: "🏠 होम वर जा",
    enterValidAmount: "योग्य रक्कम प्रविष्ट करा",
    insufficientBalance: "पुरेशी शिल्लक नाही",
    cantSendToSelf: "स्वतःच्या नंबरवर पाठवता येत नाही",
    pinHighRisk: "🔐 PIN प्रविष्ट करा (उच्च धोका)",
    transactionHistory: "व्यवहार इतिहास",
    noTransactions: "कोणतेही व्यवहार नाहीत",
    risk: "धोका",
    warning: "सावधान",
    emergency: "🆘 आणीबाणी",
    accountIsLocked: "खाते लॉक आहे",
    unlockAccount: "अनलॉक करा",
    enterPinToUnlock: "🔐 अनलॉक करण्यासाठी PIN प्रविष्ट करा",
    lockAccountDesc: "धोका असल्यास लगेच खाते लॉक करा",
    lockAccount: "🔒 खाते लॉक करा",
    safe: "🟢 सुरक्षित",
    caution: "🟡 सावधान",
    danger: "🔴 धोका",
    proceedCarefully: "कृपया सावधानीने पुढे जा",
    voiceWelcome: "रक्षाकवच मध्ये आपले स्वागत",
    voiceAskName: "तुमचे नाव सांगा",
    voiceAskPin: "तुमचा PIN प्रविष्ट करा",
    voiceLoginSuccess: "लॉगिन यशस्वी",
    voiceConfirmTx: "तुम्ही ₹{amount} {phone} ला पाठवत आहात",
    voiceFraudWarning: "हा एक धोकादायक व्यवहार असू शकतो",
    voiceAccountLocked: "खाते लॉक केले आहे",
    voiceAccountUnlocked: "खाते अनलॉक झाले आहे",
    voiceTxSuccess: "व्यवहार यशस्वी",
    voiceInsufficientBalance: "पुरेशी शिल्लक नाही",
    voiceShareNumber: "तुमचा फोन नंबर शेअर करा",
    voiceNotAvailable: "आवाज ओळख उपलब्ध नाही",
    isoCertified: "ISO 27001 प्रमाणित संरक्षण",
    nextGenEncryption: "नेक्स्ट-जेन एन्क्रिप्शन",
    encryptionDesc: "तुमचे व्यवहार मिलिटरी-ग्रेड असिमेट्रिक एन्क्रिप्शन आणि रिअल-टाइम फसवणूक देखरेखीद्वारे सुरक्षित आहेत.",
    trustVerified: "विश्वास प्रमाणित",
    trustDesc: "त्यांच्या दैनंदिन आर्थिक ऑपरेशन्ससाठी रक्षाकवचवर विश्वास ठेवणाऱ्या 2 दशलक्षाहून अधिक वापरकर्त्यांमध्ये सामील व्हा.",
    homeTab: "होम",
    vaultTab: "वाल्ह",
    shieldTab: "शिल्ड",
    profileTab: "प्रोफाइल",
    highRiskCheck: "उच्च धोका! कृपया तपशील पुन्हा एकदा तपासा।",
    guardianHelpTitle: "Guardian Help / ಸಹಾಯ ಕೇಂದ್ರ",
    emergencyHelpTitle: "🆘 आपत्कालीन मदत",
    lockAccountLabel: "खाते लॉक करा",
    helpLockAccountDesc: "तुमचे खाते त्वरित लॉक करण्यासाठी हे बटण दाबा।",
    customerCareLabel: "ग्राहक सेवा",
    customerCareDesc: "मदतीसाठी 24/7 कॉल करा।",
    fraudProtectionTitle: "⚠️ फसवणुकीपासून संरक्षण",
    neverShareOtpLabel: "OTP कधीही शेअर करू नका",
    neverShareOtpDesc: "बँक किंवा कोणीही कधीही तुमचा OTP विचारणार नाही।",
    bewareCallsLabel: "अनोळखी कॉल्सपासून सावध रहा",
    bewareCallsDesc: "अनोळखी व्यक्तींना पैसे पाठवू नका।",
    suspiciousTxLabel: "संशयास्पद व्यवहार",
    suspiciousTxDesc: "खाते त्वरित लॉक करा आणि मदत घ्या।",
    guardianAssistTitle: "👨‍👩‍👧 पालक सहाय्यक",
    callGuardianLabel: "पालकांना कॉल करा",
    callGuardianDesc: "तुमच्या कुटुंबातील सदस्यांकडून मदत घ्या।",
    permissionReqLabel: "परवानगी आवश्यक",
    permissionReqDesc: "मोठ्या व्यवहारांसाठी पालकांची परवानगी आवश्यक आहे।",
    guidanceTitle: "📘 मदत आणि मार्गदर्शन",
    howToSendLabel: "पैसे कसे पाठवायचे",
    howToSendDesc: "पैसे पाठवा वर क्लिक करा, नंबर आणि रक्कम टाका।",
    useQrLabel: "QR कोड वापरणे",
    useQrDesc: "स्कॅन करा आणि सहज पैसे पाठवा।",
    forgotPinLabel: "PIN विसरलात",
    forgotPinDesc: "रीसेट करण्यासाठी मदत केंद्राशी संपर्क साधा।",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language | null>(() => {
    const saved = localStorage.getItem("rakshakavach_language");
    return saved ? (saved as Language) : null;
  });

  const setLanguage = (lang: Language) => {
    localStorage.setItem("rakshakavach_language", lang);
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    if (!language) return key;
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const speechCode = language ? LANGUAGE_CONFIG[language].speechCode : "en-IN";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, speechCode }}>
      {children}
    </LanguageContext.Provider>
  );
}
